// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMNcjokrxVVM1F-Xc8sPsBWt8DJc5hWoU',
    appId: '1:749587351576:web:b513448d6f34ca1dc39b6d',
    messagingSenderId: '749587351576',
    projectId: 'aimltest-cb76a',
    authDomain: 'aimltest-cb76a.firebaseapp.com',
    storageBucket: 'aimltest-cb76a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsmt4V5fctS8cQbO6wgCMAXPCXpepU6k',
    appId: '1:749587351576:android:2af366d744c855e8c39b6d',
    messagingSenderId: '749587351576',
    projectId: 'aimltest-cb76a',
    storageBucket: 'aimltest-cb76a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8OVfm2OuNzs60lTk4UsXIjttIV6KeYT4',
    appId: '1:749587351576:ios:d9173206da1926fac39b6d',
    messagingSenderId: '749587351576',
    projectId: 'aimltest-cb76a',
    storageBucket: 'aimltest-cb76a.appspot.com',
    iosBundleId: 'com.example.aimlMobile2024',
  );
}
