// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7nMv0CNTjdyL3cRHJQohBStH61z_5N7U',
    appId: '1:641700180697:web:7491deffaadd1050b2c4c8',
    messagingSenderId: '641700180697',
    projectId: 'aiml-server-2024',
    authDomain: 'aiml-server-2024.firebaseapp.com',
    storageBucket: 'aiml-server-2024.appspot.com',
    measurementId: 'G-DKBCKJ994Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaO-xGKuVlVU7LK3nuUvfujkAqx9Hv_MY',
    appId: '1:641700180697:android:7fba052e2c76d756b2c4c8',
    messagingSenderId: '641700180697',
    projectId: 'aiml-server-2024',
    storageBucket: 'aiml-server-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuuiiJcc6Hfq-WV62UiagWEU2yP0asiIY',
    appId: '1:641700180697:ios:f1b48e9562fefc9bb2c4c8',
    messagingSenderId: '641700180697',
    projectId: 'aiml-server-2024',
    storageBucket: 'aiml-server-2024.appspot.com',
    iosBundleId: 'com.example.aimlMobile2024',
  );

}